baseurl: /
url: "http://codingdavinci.de"
registerurl: /anmeldung/
markdown: kramdown

sass:
  style: compressed

permalink: /news/:year/:month/:day/:title.html

gems: [jekyll-paginate]


paginate: 7
paginate_path: "/news/page:num/"